### ISSUE TITLE
latest brew is installing 1.17.2.rc1 (rather than stable 1.17.1) and crashing on launch...

### ISSUE THREAD

**Issue by smagdali** [filecoin-project/homebrew-lotus#16]
possibly should be 2 separate issues, sorry. 

stefan@StefMacBookPro ~ % lotus
dyld[13612]: symbol not found in flat namespace (_hwloc_bitmap_alloc)
zsh: abort      lotus
stefan@StefMacBookPro ~ % 

feels like we really need something that tests that the binary can execute as part of the CI?

**Comment by ianconsolata** [comment]
Testing is a good idea. Not sure exactly how to test the M1, maybe using Cory's runner. I can probably even use that for the build now.

Does downloading binary manually work for you? https://github.com/filecoin-project/lotus/releases/tag/v1.17.2-rc1

**Comment by ianconsolata** [comment]
Also, probably shouldn't have updated homebrew for this at all? At least not until 1.17.2 stable.

**Comment by smagdali** [comment]
can confirm that directly downloaded binary also crashes

**Comment by ianconsolata** [comment]
I think with the work we did today, we can close this? We're no longer publishing RC builds, and the 1.17.1 release should work on M1s now.
