### ISSUE TITLE
Getting [lotus-worker] Error 1 when installing

### ISSUE THREAD

**Issue by jousi592** [filecoin-project/homebrew-lotus#8]
Environment: 2021 MacBook Pro (12.0.1), ARM architecture.
Homebrew has been updated and upgrated.

When I run the `brew install lotus` command, I get:
```
Already downloaded: /Users/josef1/Library/Caches/Homebrew/downloads/9c4142aad51c88bc3c10b00efb944ff0f3b886a8b393d9f7c5632f9b5a2adf1c--lotus-1.13.0.tar.gz
==> Installing lotus from filecoin-project/lotus
==> git clone https://github.com/filecoin-project/filecoin-ffi.git extern/filecoin-ffi
==> git clone https://github.com/filecoin-project/serialization-vectors.git extern/serialization-vectors
==> git clone https://github.com/filecoin-project/test-vectors.git extern/test-vectors
==> touch build/.update-modules
==> make all
Last 15 lines from /Users/josef1/Library/Logs/Homebrew/lotus/05.make:
go: downloading github.com/ipfs/go-filestore v1.0.0
go: downloading github.com/ipfs/go-ipfs-chunker v0.0.5
go: github.com/filecoin-project/filecoin-ffi@v0.30.4-0.20200910194244-f640612a1a1f requires
	github.com/filecoin-project/go-state-types@v0.1.1: missing go.sum entry; to add it:
	go mod download github.com/filecoin-project/go-state-types
go: github.com/filecoin-project/filecoin-ffi@v0.30.4-0.20200910194244-f640612a1a1f requires
	github.com/filecoin-project/go-state-types@v0.1.1: missing go.sum entry; to add it:
	go mod download github.com/filecoin-project/go-state-types
go: github.com/filecoin-project/filecoin-ffi@v0.30.4-0.20200910194244-f640612a1a1f requires
	github.com/filecoin-project/go-state-types@v0.1.1: missing go.sum entry; to add it:
	go mod download github.com/filecoin-project/go-state-types
make: *** [lotus-worker] Error 1
make: *** Waiting for unfinished jobs....
make: *** [lotus-miner] Error 1
make: *** [lotus] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/filecoin-project/homebrew-lotus/issues
```

Any ideas what I might be missing?

**Comment by JasontheNomad** [comment]
I'm getting the same error. Has anyone found a solution?

**Comment by Leozhang404** [comment]
no idea

**Comment by serinuntius** [comment]
I'm getting the same error.

**Comment by leedsrising** [comment]
Getting the same error

**Comment by 0x77dev** [comment]
Same on Intel

**Comment by SgtPooki** [comment]
I was able to get it to install on my machine by altering the recipe with fixes found while stepping through `brew install -vd lotus`.

Someone more familiar with Go might be able to tidy it up a bit, but you can see the changes made here: https://github.com/SgtPooki/homebrew-lotus/pull/1/files 

And to test it before any changes are made to the official recipe, you can run the following:

```bash
brew tap SgtPooki/lotus
brew install sgtpooki/lotus/lotus
```

**Comment by BigLep** [comment]
@SgtPooki : want to surface a PR for this?

**Comment by SgtPooki** [comment]
@BigLep absolutely. I was just waiting to verify that it fixed the problem for a few additional users. Have you tried the updated recipe?

**Comment by dleonx** [comment]
@SgtPooki I was able to install lotus successfully with that fix!

**Comment by SgtPooki** [comment]
> Same on Intel

@0x77dev When you say you're getting the same on an intel CPU, can you clarify whether you're using `arch -x86_64 brew install lotus` on an M1 mac or if you're using an intel/non-M1 mac entirely?

**Comment by smagdali** [comment]
Successfully installed on Monterey 12.2.1

**Comment by mr-spaghetti-code** [comment]
Working on my M1 Macbook Pro Monterey 12.2 (21D49). Thanks for the fix!
